version: "3"

services:
  web:
    container_name: web
    build: ./php
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./zf1-developer-example:/var/www/html"
      - "./php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./php/.htaccess:/var/www/html/public/.htaccess"
    ports:
      - 8081:80
  mysql:
    container_name: mysql_host
    build: ./mysql/
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zf
      - MYSQL_USER=zf
      - MYSQL_PASSWORD=password
      - TZ='Asia/Tokyo'

  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8082:80